---
cache: /home/nranawakaara/Projects/samesh/outputs/mesh_segmentation_cache
cache_overwrite: False
output: /home/nranawakaara/Projects/samesh/outputs/mesh_segmentation_output

sam:
  sam:
    checkpoint: /home/nranawakaara/Projects/samesh/third_party/segment-anything-2/checkpoints/sam2_hiera_large.pt
    model_config: sam2_hiera_l.yaml
    auto: True
    ground: False
    engine_config:
      points_per_side: 32
      crop_n_layers: 0
      #min_mask_region_area: 1024 # sam2 breaks since it uses C connected components
      pred_iou_thresh: 0.5
      stability_score_thresh: 0.7
      stability_score_offset: 1.0

sam_mesh:
  use_modes: ['sdf', 'norms']
  min_area: 1024
  connections_bin_resolution: 100
  connections_bin_threshold_percentage: 0.125
  smoothing_threshold_percentage_size: 0.025
  smoothing_threshold_percentage_area: 0.025
  smoothing_iterations: 64
  repartition_cost: 1
  repartition_lambda: 6
  repartition_iterations: 1
  connections_threshold: 0

renderer:
  target_dim: [1024, 1024]
  camera_generation_method: icosahedron #octohedron
  renderer_args:
    interpolate_norms: True
  sampling_args: {radius: 2.5}
  bg_color: [0.5, 0.5, 0.5]
  smooth: False
  lighting_args: {alpha: 0.1, beta: 0.1, ambient_light: [1.0, 1.0, 1.0]}